/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface NonfungibleTokenPositionDescriptorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH9"
      | "flipRatio"
      | "nativeCurrencyLabel"
      | "nativeCurrencyLabelBytes"
      | "tokenRatioPriority"
      | "tokenURI"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETH9", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "flipRatio",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nativeCurrencyLabel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nativeCurrencyLabelBytes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenRatioPriority",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "WETH9", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flipRatio", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nativeCurrencyLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nativeCurrencyLabelBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenRatioPriority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
}

export interface NonfungibleTokenPositionDescriptor extends BaseContract {
  connect(runner?: ContractRunner | null): NonfungibleTokenPositionDescriptor;
  waitForDeployment(): Promise<this>;

  interface: NonfungibleTokenPositionDescriptorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WETH9: TypedContractMethod<[], [string], "view">;

  flipRatio: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, chainId: BigNumberish],
    [boolean],
    "view"
  >;

  nativeCurrencyLabel: TypedContractMethod<[], [string], "view">;

  nativeCurrencyLabelBytes: TypedContractMethod<[], [string], "view">;

  tokenRatioPriority: TypedContractMethod<
    [token: AddressLike, chainId: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<
    [positionManager: AddressLike, tokenId: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WETH9"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flipRatio"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike, chainId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nativeCurrencyLabel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nativeCurrencyLabelBytes"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenRatioPriority"
  ): TypedContractMethod<
    [token: AddressLike, chainId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<
    [positionManager: AddressLike, tokenId: BigNumberish],
    [string],
    "view"
  >;

  filters: {};
}
