/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC1363Spender,
  IERC1363SpenderInterface,
} from "../../interfaces/IERC1363Spender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onApprovalReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC1363Spender__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1363SpenderInterface {
    return new utils.Interface(_abi) as IERC1363SpenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1363Spender {
    return new Contract(address, _abi, signerOrProvider) as IERC1363Spender;
  }
}
