/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as aaveV2 from "./aave-v2";
import type * as aaveV3 from "./aave-v3";
import type * as compound from "./compound";

export type { aaveV2 };

export type { aaveV3 };

export type { compound };
