/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BackedWhitelistController } from "./BackedWhitelistController";
export type { BackedWhitelistControllerAggregator } from "./BackedWhitelistControllerAggregator";
